spring.application.name=trip-planner-api
spring.config.import=classpath:usage.properties,classpath:trip-image.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/trip_planner
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://proven-snail-10.clerk.accounts.dev/.well-known/jwks.json

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

#logging.level.root=DEBUG