spring.datasource.url=jdbc:postgresql://localhost:5432/trip_planner
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://proven-snail-10.clerk.accounts.dev
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://proven-snail-10.clerk.accounts.dev/.well-known/jwks.json